# Generated by Django 4.1 on 2022-08-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, null=True)),
                ('roles', models.CharField(db_column='role_list', max_length=200, null=True)),
                ('gender',
                 models.CharField(choices=[('FEMALE', 0), ('MALE', 1)], db_column='sex', max_length=10, null=True)),
                ('current_token', models.CharField(db_column='login_token', max_length=36, null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
