# Generated by Django 4.1 on 2022-09-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=2048)),
                ('email', models.CharField(max_length=100, null=True)),
                ('roles', models.CharField(db_column='role_list', max_length=200, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'FEMALE'), (1, 'MALE')], db_column='gender', null=True)),
                ('dob', models.DateField(db_column='date_of_birth', null=True)),
            ],
            options={
                'db_table': 't_user',
            },
        ),
    ]
