# Generated by Django 4.1 on 2022-08-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(db_column='date_of_birth', null=True),
        ),
    ]
