# Generated by Django 4.1 on 2022-09-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_column='path', max_length=2048)),
                ('created_date', models.DateTimeField(db_column='created_date')),
                ('created_user_id', models.IntegerField(db_column='created_user_id')),
            ],
            options={
                'db_table': 't_filemeta',
            },
        ),
    ]
