# Generated by Django 4.1 on 2022-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(db_column='role_list', max_length=200, null=True),
        ),
    ]
