# Generated by Django 4.1 on 2022-08-19 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_value', models.CharField(db_column='token_value', max_length=36, null=True)),
                ('created_datetime', models.DateTimeField(db_column='created_time')),
            ],
            options={
                'db_table': 't_user_token',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_token',
        ),
        migrations.AddField(
            model_name='user',
            name='user_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.usertoken'),
        ),
    ]
