# Generated by Django 4.1 on 2022-08-19 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0003_usertoken_remove_user_current_token_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='application.usertoken'),
        ),
    ]
