# Generated by Django 4.1 on 2022-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[('FEMALE', 0), ('MALE', 1)], db_column='sex', max_length=10, null=True),
        ),
    ]
