# Generated by Django 4.1 on 2022-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_user_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='token_value',
            field=models.CharField(db_column='token_value', max_length=2000, null=True),
        ),
    ]
