# Generated by Django 4.1 on 2022-08-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_usertoken_token_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_token',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
